extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const MacroObject ccm_area_2_macro_objs[];
extern const GeoLayout ccm_area_3_geo[];
extern const GeoLayout ccm_area_3[];
extern const Collision ccm_area_3_collision[];
extern const MacroObject ccm_area_3_macro_objs[];
extern const GeoLayout ccm_area_4_geo[];
extern const GeoLayout ccm_area_4[];
extern const Collision ccm_area_4_collision[];
extern const MacroObject ccm_area_4_macro_objs[];
extern Lights1 ccm_dl_Darkness_lights;
extern Vtx ccm_dl_Cube_016_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_016_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_017_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_017_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_018_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_018_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_019_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_019_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_020_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_020_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_021_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_021_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_022_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_022_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_023_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_Cube_023_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_Darkness[];
extern Gfx ccm_dl_Cube_016_mesh_layer_1[];
extern Gfx ccm_dl_Cube_017_mesh_layer_1[];
extern Gfx ccm_dl_Cube_018_mesh_layer_1[];
extern Gfx ccm_dl_Cube_019_mesh_layer_1[];
extern Gfx ccm_dl_Cube_020_mesh_layer_1[];
extern Gfx ccm_dl_Cube_021_mesh_layer_1[];
extern Gfx ccm_dl_Cube_022_mesh_layer_1[];
extern Gfx ccm_dl_Cube_023_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
