extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern Lights1 sa_dl_black_lights;
extern Vtx sa_dl_Cube_006_mesh_layer_1_vtx_0[24];
extern Gfx sa_dl_Cube_006_mesh_layer_1_tri_0[];
extern Gfx mat_sa_dl_black[];
extern Gfx mat_revert_sa_dl_black[];
extern Gfx sa_dl_Cube_006_mesh_layer_1[];
extern Gfx sa_dl_material_revert_render_settings[];
