#include "src/game/envfx_snow.h"

const GeoLayout wf_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3651, -3168, -63, wf_dl_Cube_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3601, -3168, -27, wf_dl_Cube_008_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -2007, 4000, 0, wf_dl_DL_sl_1_0xe0a7ba0_Obj_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(4, -2007, 4754, 0, wf_dl_DL_sl_1_0xe0a7ba0_Obj_004_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, wf_dl_DL_sl_1_0xe0a7ba0_Obj_004_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -2007, 4754, 0, wf_dl_DL_sl_1_0xe0a7ba0_Obj_005_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, wf_dl_DL_sl_1_0xe0a7ba0_Obj_005_mesh_layer_4),
			GEO_DISPLAY_LIST(5, wf_dl_DL_sl_1_0xe0a7ba0_Obj_005_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(5, -2007, 4000, 0, wf_dl_DL_sl_1_0xe0c43d0_Obj_002_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wf_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 3585, -777, 0, 3585, -1027, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, wf_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(5, wf_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, wf_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, wf_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
