extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern Lights1 bob_dl_Darkness_lights;
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_005_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_006_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_006_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_007_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_007_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Darkness[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Cube_003_mesh_layer_1[];
extern Gfx bob_dl_Cube_004_mesh_layer_1[];
extern Gfx bob_dl_Cube_005_mesh_layer_1[];
extern Gfx bob_dl_Cube_006_mesh_layer_1[];
extern Gfx bob_dl_Cube_007_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
