extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_4_geo[];
extern const GeoLayout wf_area_4[];
extern const Collision wf_area_4_collision[];
extern const MacroObject wf_area_4_macro_objs[];
extern Lights1 wf_dl_Darkness_lights;
extern Vtx wf_dl_Cube_008_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_008_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_009_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_009_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_010_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_010_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_011_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_011_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_012_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_012_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_013_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_013_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_014_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_014_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_015_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_015_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_Darkness[];
extern Gfx wf_dl_Cube_008_mesh_layer_1[];
extern Gfx wf_dl_Cube_009_mesh_layer_1[];
extern Gfx wf_dl_Cube_010_mesh_layer_1[];
extern Gfx wf_dl_Cube_011_mesh_layer_1[];
extern Gfx wf_dl_Cube_012_mesh_layer_1[];
extern Gfx wf_dl_Cube_013_mesh_layer_1[];
extern Gfx wf_dl_Cube_014_mesh_layer_1[];
extern Gfx wf_dl_Cube_015_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
